trigger:
  branches:
    include:
      - main

variables:
  - group: VercelSecrets  # 👈 This connects to the variable group with your VERCEL_TOKEN

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install -g vercel
    displayName: 'Install Vercel CLI'

  - script: vercel --prod --token=$(VERCEL_TOKEN)
    displayName: 'Deploy to Vercel'
