trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vercel-token-group   # Only if you're using a Variable Group

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install -g vercel
    displayName: 'Install Vercel CLI'

  - script: vercel --prod --yes --token=$(VERCEL_TOKEN)
    displayName: 'Deploy to Vercel'

